on:
  push:
    branches:
      - master

jobs:
  deploy-to-digital-ocean-droplet:
    runs-on: ubuntu-latest
    name: Bot
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Pull from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: cd ~/ilovertx3000 && git pull https://github.com/tkarssli/ilovertx3000.git
      - name: Stop docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: cd ~/ilovertx3000  && docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
      - name: Docker Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: cd ~/ilovertx3000 && docker build -t statusbot .
      - name: Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: cd ~/ilovertx3000 && docker run -d statusbot
